package objstore

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"github.com/stoicsoft/vpsbox/internal/executil"
)

// garageConfig is everything that varies in the generated garage.toml. Ports are
// allocated per start, so the file is rewritten each time rather than being
// treated as user-editable.
type garageConfig struct {
	MetaDir    string
	DataDir    string
	APIPort    int
	RPCPort    int
	AdminPort  int
	Region     string
	RootDomain string
	RPCSecret  string
	AdminToken string
}

// renderGarageConfig produces the server's configuration file.
//
// The S3 API binds to every interface because sandboxes reach it over the
// hypervisor's private bridge, whose host-side address is not knowable until a
// VM tells us. The RPC and admin listeners stay on loopback — nothing outside
// this machine has any business talking to them.
func renderGarageConfig(cfg garageConfig) string {
	var b strings.Builder

	b.WriteString("# Generated by vpsbox. Rewritten on every start — edits will be lost.\n")
	fmt.Fprintf(&b, "metadata_dir = %q\n", cfg.MetaDir)
	fmt.Fprintf(&b, "data_dir = %q\n", cfg.DataDir)
	b.WriteString("db_engine = \"sqlite\"\n\n")

	// One copy of each object: this is a single node on a laptop, and asking for
	// replicas would leave the cluster permanently degraded.
	b.WriteString("replication_factor = 1\n\n")

	fmt.Fprintf(&b, "rpc_bind_addr = \"127.0.0.1:%d\"\n", cfg.RPCPort)
	fmt.Fprintf(&b, "rpc_public_addr = \"127.0.0.1:%d\"\n", cfg.RPCPort)
	fmt.Fprintf(&b, "rpc_secret = %q\n\n", cfg.RPCSecret)

	b.WriteString("[s3_api]\n")
	fmt.Fprintf(&b, "s3_region = %q\n", cfg.Region)
	fmt.Fprintf(&b, "api_bind_addr = \"0.0.0.0:%d\"\n", cfg.APIPort)
	// The leading dot is what makes <bucket>.buckets.vpsbox.local resolve to a
	// bucket instead of being read as a hostname.
	fmt.Fprintf(&b, "root_domain = \".%s\"\n\n", cfg.RootDomain)

	b.WriteString("[admin]\n")
	fmt.Fprintf(&b, "api_bind_addr = \"127.0.0.1:%d\"\n", cfg.AdminPort)
	fmt.Fprintf(&b, "admin_token = %q\n", cfg.AdminToken)

	return b.String()
}

// garageCLI runs a `garage` subcommand against our config. The CLI authenticates
// to the daemon with the rpc_secret in that file, so every admin action has to go
// through it.
func (m *Manager) garageCLI(ctx context.Context, args ...string) (string, error) {
	full := append([]string{"-c", m.configPath()}, args...)
	result, err := executil.Run(ctx, binary, full...)
	if err != nil {
		return result.Stdout, err
	}
	return result.Stdout, nil
}

// parseNodeID pulls the node identifier out of `garage node id`, which prints
// "<64-hex-id>@<host>:<port>" followed by connection instructions.
func parseNodeID(out string) (string, bool) {
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimSpace(line)
		id, _, found := strings.Cut(line, "@")
		if !found {
			continue
		}
		// A node ID is hex; anything else is prose from the help text below it.
		if len(id) < 16 || !isHex(id) {
			continue
		}
		return id, true
	}
	return "", false
}

func isHex(value string) bool {
	for _, r := range value {
		isDigit := r >= '0' && r <= '9'
		isLower := r >= 'a' && r <= 'f'
		isUpper := r >= 'A' && r <= 'F'
		if !isDigit && !isLower && !isUpper {
			return false
		}
	}
	return len(value) > 0
}

// parseLayoutVersion reads the version out of `garage layout show`, which ends
// with "Current cluster layout version: N". A fresh cluster reports 0.
func parseLayoutVersion(out string) (int, bool) {
	const marker = "Current cluster layout version:"
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, marker) {
			continue
		}
		value := strings.TrimSpace(strings.TrimPrefix(line, marker))
		version, err := strconv.Atoi(value)
		if err != nil {
			return 0, false
		}
		return version, true
	}
	return 0, false
}

// layoutUnassigned reports whether `garage status` shows a node with no storage
// role. A node in that state accepts no S3 traffic at all, which is why a fresh
// server needs the layout step before it is usable.
func layoutUnassigned(status string) bool {
	return strings.Contains(status, "NO ROLE ASSIGNED")
}

// ensureLayout gives the node a storage role if it does not have one. This is the
// one-time cluster bootstrap; on every later start the layout is already in the
// metadata directory and this is a no-op.
func (m *Manager) ensureLayout(ctx context.Context, report func(string)) error {
	status, err := m.garageCLI(ctx, "status")
	if err != nil {
		return fmt.Errorf("read object store status: %w", err)
	}
	if !layoutUnassigned(status) {
		return nil
	}

	report("Preparing the object store for first use…")

	idOut, err := m.garageCLI(ctx, "node", "id")
	if err != nil {
		return fmt.Errorf("read object store node id: %w", err)
	}
	nodeID, ok := parseNodeID(idOut)
	if !ok {
		return fmt.Errorf("could not read the object store node id from:\n%s", idOut)
	}

	showOut, err := m.garageCLI(ctx, "layout", "show")
	if err != nil {
		return fmt.Errorf("read object store layout: %w", err)
	}
	current, ok := parseLayoutVersion(showOut)
	if !ok {
		// A cluster that has never been laid out may not print a version at all.
		current = 0
	}

	if _, err := m.garageCLI(ctx, "layout", "assign", "-z", layoutZone, "-c", layoutCapacity, nodeID); err != nil {
		return fmt.Errorf("assign object store layout: %w", err)
	}
	if _, err := m.garageCLI(ctx, "layout", "apply", "--version", strconv.Itoa(current+1)); err != nil {
		return fmt.Errorf("apply object store layout: %w", err)
	}
	return nil
}

// ensureKey makes sure the S3 credentials vpsbox generated are installed on the
// server and may create buckets. Importing our own key rather than letting the
// server mint one is what lets credentials survive a wiped metadata directory —
// sandboxes already have the old key written into ~/.aws/credentials.
func (m *Manager) ensureKey(ctx context.Context, accessKey, secretKey string) error {
	// `key info` exits non-zero when the key is unknown, which is the cheapest
	// reliable existence check; importing a duplicate is an error.
	if _, err := m.garageCLI(ctx, "key", "info", accessKey); err != nil {
		if _, err := m.garageCLI(ctx, "key", "import", "--yes", "-n", keyName, accessKey, secretKey); err != nil {
			return fmt.Errorf("install object store credentials: %w", err)
		}
	}

	// Idempotent, and required: without it the S3 CreateBucket call is refused.
	if _, err := m.garageCLI(ctx, "key", "allow", "--create-bucket", accessKey); err != nil {
		return fmt.Errorf("grant bucket creation to the object store key: %w", err)
	}
	return nil
}
