// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetState():Promise<main.AppState>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenShell(arg1:string):Promise<void>;

export function StartCreateSandbox(arg1:main.CreateSandboxInput):Promise<string>;

export function StartDestroySandbox(arg1:string):Promise<string>;

export function StartFixLocalDomains():Promise<string>;

export function StartGenerateSSHKey(arg1:string):Promise<string>;

export function StartInstallPackages():Promise<string>;

export function StartStartSandbox(arg1:string):Promise<string>;

export function StartStopSandbox(arg1:string):Promise<string>;

export function StartUpdateSandbox(arg1:main.UpdateSandboxInput):Promise<string>;
