// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState() {
  return window['go']['main']['DesktopApp']['GetState']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['DesktopApp']['OpenExternal'](arg1);
}

export function OpenShell(arg1) {
  return window['go']['main']['DesktopApp']['OpenShell'](arg1);
}

export function StartCreateSandbox(arg1) {
  return window['go']['main']['DesktopApp']['StartCreateSandbox'](arg1);
}

export function StartDestroySandbox(arg1) {
  return window['go']['main']['DesktopApp']['StartDestroySandbox'](arg1);
}

export function StartFixLocalDomains() {
  return window['go']['main']['DesktopApp']['StartFixLocalDomains']();
}

export function StartGenerateSSHKey(arg1) {
  return window['go']['main']['DesktopApp']['StartGenerateSSHKey'](arg1);
}

export function StartInstallPackages() {
  return window['go']['main']['DesktopApp']['StartInstallPackages']();
}

export function StartStartSandbox(arg1) {
  return window['go']['main']['DesktopApp']['StartStartSandbox'](arg1);
}

export function StartStopSandbox(arg1) {
  return window['go']['main']['DesktopApp']['StartStopSandbox'](arg1);
}

export function StartUpdateSandbox(arg1) {
  return window['go']['main']['DesktopApp']['StartUpdateSandbox'](arg1);
}
