// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['DesktopApp']['ApplyUpdate']();
}

export function CancelUpdateDownload() {
  return window['go']['main']['DesktopApp']['CancelUpdateDownload']();
}

export function CheckForUpdate() {
  return window['go']['main']['DesktopApp']['CheckForUpdate']();
}

export function CheckWorkspaceReachability(arg1, arg2) {
  return window['go']['main']['DesktopApp']['CheckWorkspaceReachability'](arg1, arg2);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['DesktopApp']['CreateWorkspace'](arg1);
}

export function GetObjectStore() {
  return window['go']['main']['DesktopApp']['GetObjectStore']();
}

export function GetServerDiff(arg1) {
  return window['go']['main']['DesktopApp']['GetServerDiff'](arg1);
}

export function GetServerLogs(arg1) {
  return window['go']['main']['DesktopApp']['GetServerLogs'](arg1);
}

export function GetState() {
  return window['go']['main']['DesktopApp']['GetState']();
}

export function ListApps(arg1) {
  return window['go']['main']['DesktopApp']['ListApps'](arg1);
}

export function ListSnapshots(arg1) {
  return window['go']['main']['DesktopApp']['ListSnapshots'](arg1);
}

export function ListTemplates() {
  return window['go']['main']['DesktopApp']['ListTemplates']();
}

export function ListWorkspaces() {
  return window['go']['main']['DesktopApp']['ListWorkspaces']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['DesktopApp']['OpenExternal'](arg1);
}

export function OpenShell(arg1) {
  return window['go']['main']['DesktopApp']['OpenShell'](arg1);
}

export function PickSSHKey() {
  return window['go']['main']['DesktopApp']['PickSSHKey']();
}

export function PreviewImportVPS(arg1) {
  return window['go']['main']['DesktopApp']['PreviewImportVPS'](arg1);
}

export function PreviewPush(arg1) {
  return window['go']['main']['DesktopApp']['PreviewPush'](arg1);
}

export function ReadSSHKeys(arg1) {
  return window['go']['main']['DesktopApp']['ReadSSHKeys'](arg1);
}

export function RevealKeyFolder(arg1) {
  return window['go']['main']['DesktopApp']['RevealKeyFolder'](arg1);
}

export function StartAttachBuckets(arg1) {
  return window['go']['main']['DesktopApp']['StartAttachBuckets'](arg1);
}

export function StartCheckpoint(arg1, arg2) {
  return window['go']['main']['DesktopApp']['StartCheckpoint'](arg1, arg2);
}

export function StartCreateBucket(arg1) {
  return window['go']['main']['DesktopApp']['StartCreateBucket'](arg1);
}

export function StartCreateSandbox(arg1) {
  return window['go']['main']['DesktopApp']['StartCreateSandbox'](arg1);
}

export function StartDeleteBucket(arg1, arg2) {
  return window['go']['main']['DesktopApp']['StartDeleteBucket'](arg1, arg2);
}

export function StartDeleteSnapshot(arg1, arg2) {
  return window['go']['main']['DesktopApp']['StartDeleteSnapshot'](arg1, arg2);
}

export function StartDeploy(arg1, arg2) {
  return window['go']['main']['DesktopApp']['StartDeploy'](arg1, arg2);
}

export function StartDestroySandbox(arg1) {
  return window['go']['main']['DesktopApp']['StartDestroySandbox'](arg1);
}

export function StartDestroyWorkspace(arg1) {
  return window['go']['main']['DesktopApp']['StartDestroyWorkspace'](arg1);
}

export function StartDownloadUpdate() {
  return window['go']['main']['DesktopApp']['StartDownloadUpdate']();
}

export function StartFixLocalDomains() {
  return window['go']['main']['DesktopApp']['StartFixLocalDomains']();
}

export function StartGenerateSSHKey(arg1) {
  return window['go']['main']['DesktopApp']['StartGenerateSSHKey'](arg1);
}

export function StartImportFromVPS(arg1) {
  return window['go']['main']['DesktopApp']['StartImportFromVPS'](arg1);
}

export function StartInstallPackages() {
  return window['go']['main']['DesktopApp']['StartInstallPackages']();
}

export function StartJoinWorkspace(arg1, arg2) {
  return window['go']['main']['DesktopApp']['StartJoinWorkspace'](arg1, arg2);
}

export function StartLeaveWorkspace(arg1, arg2) {
  return window['go']['main']['DesktopApp']['StartLeaveWorkspace'](arg1, arg2);
}

export function StartPushToVPS(arg1) {
  return window['go']['main']['DesktopApp']['StartPushToVPS'](arg1);
}

export function StartRestoreSnapshot(arg1, arg2) {
  return window['go']['main']['DesktopApp']['StartRestoreSnapshot'](arg1, arg2);
}

export function StartStartSandbox(arg1) {
  return window['go']['main']['DesktopApp']['StartStartSandbox'](arg1);
}

export function StartStopObjectStore() {
  return window['go']['main']['DesktopApp']['StartStopObjectStore']();
}

export function StartStopSandbox(arg1) {
  return window['go']['main']['DesktopApp']['StartStopSandbox'](arg1);
}

export function StartSyncWorkspace(arg1) {
  return window['go']['main']['DesktopApp']['StartSyncWorkspace'](arg1);
}

export function StartUpdateSandbox(arg1) {
  return window['go']['main']['DesktopApp']['StartUpdateSandbox'](arg1);
}
