// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['DesktopApp']['CheckForUpdate']();
}

export function GetServerDiff(arg1) {
  return window['go']['main']['DesktopApp']['GetServerDiff'](arg1);
}

export function GetServerLogs(arg1) {
  return window['go']['main']['DesktopApp']['GetServerLogs'](arg1);
}

export function GetState() {
  return window['go']['main']['DesktopApp']['GetState']();
}

export function ListSnapshots(arg1) {
  return window['go']['main']['DesktopApp']['ListSnapshots'](arg1);
}

export function ListTemplates() {
  return window['go']['main']['DesktopApp']['ListTemplates']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['DesktopApp']['OpenExternal'](arg1);
}

export function OpenShell(arg1) {
  return window['go']['main']['DesktopApp']['OpenShell'](arg1);
}

export function ReadSSHKeys(arg1) {
  return window['go']['main']['DesktopApp']['ReadSSHKeys'](arg1);
}

export function RevealKeyFolder(arg1) {
  return window['go']['main']['DesktopApp']['RevealKeyFolder'](arg1);
}

export function StartCheckpoint(arg1, arg2) {
  return window['go']['main']['DesktopApp']['StartCheckpoint'](arg1, arg2);
}

export function StartCreateSandbox(arg1) {
  return window['go']['main']['DesktopApp']['StartCreateSandbox'](arg1);
}

export function StartDeleteSnapshot(arg1, arg2) {
  return window['go']['main']['DesktopApp']['StartDeleteSnapshot'](arg1, arg2);
}

export function StartDeploy(arg1, arg2) {
  return window['go']['main']['DesktopApp']['StartDeploy'](arg1, arg2);
}

export function StartDestroySandbox(arg1) {
  return window['go']['main']['DesktopApp']['StartDestroySandbox'](arg1);
}

export function StartFixLocalDomains() {
  return window['go']['main']['DesktopApp']['StartFixLocalDomains']();
}

export function StartGenerateSSHKey(arg1) {
  return window['go']['main']['DesktopApp']['StartGenerateSSHKey'](arg1);
}

export function StartInstallPackages() {
  return window['go']['main']['DesktopApp']['StartInstallPackages']();
}

export function StartRestoreSnapshot(arg1, arg2) {
  return window['go']['main']['DesktopApp']['StartRestoreSnapshot'](arg1, arg2);
}

export function StartStartSandbox(arg1) {
  return window['go']['main']['DesktopApp']['StartStartSandbox'](arg1);
}

export function StartStopSandbox(arg1) {
  return window['go']['main']['DesktopApp']['StartStopSandbox'](arg1);
}

export function StartUpdateSandbox(arg1) {
  return window['go']['main']['DesktopApp']['StartUpdateSandbox'](arg1);
}
