// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktopbackend} from '../models';

export function ApplyUpdate():Promise<void>;

export function CancelUpdateDownload():Promise<void>;

export function CheckForUpdate():Promise<desktopbackend.UpdateInfo>;

export function CheckWorkspaceReachability(arg1:string,arg2:string):Promise<Record<string, boolean>>;

export function CreateWorkspace(arg1:string):Promise<desktopbackend.Workspace>;

export function GetObjectStore():Promise<desktopbackend.ObjectStore>;

export function GetServerDiff(arg1:string):Promise<desktopbackend.ServerDiff>;

export function GetServerLogs(arg1:string):Promise<desktopbackend.ServerLogs>;

export function GetState():Promise<desktopbackend.AppState>;

export function ListApps(arg1:string):Promise<Array<desktopbackend.LiveApp>>;

export function ListSnapshots(arg1:string):Promise<desktopbackend.SnapshotList>;

export function ListTemplates():Promise<Array<desktopbackend.DeployTemplate>>;

export function ListWorkspaces():Promise<Array<desktopbackend.Workspace>>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenShell(arg1:string):Promise<void>;

export function PickSSHKey():Promise<string>;

export function PreviewImportVPS(arg1:desktopbackend.ImportVPSInput):Promise<desktopbackend.ImportPreview>;

export function PreviewPush(arg1:desktopbackend.PushInput):Promise<desktopbackend.TransferPlan>;

export function ReadSSHKeys(arg1:string):Promise<desktopbackend.SSHKeys>;

export function RevealKeyFolder(arg1:string):Promise<void>;

export function StartAttachBuckets(arg1:string):Promise<string>;

export function StartCheckpoint(arg1:string,arg2:string):Promise<string>;

export function StartCreateBucket(arg1:string):Promise<string>;

export function StartCreateSandbox(arg1:desktopbackend.CreateSandboxInput):Promise<string>;

export function StartDeleteBucket(arg1:string,arg2:boolean):Promise<string>;

export function StartDeleteSnapshot(arg1:string,arg2:string):Promise<string>;

export function StartDeploy(arg1:string,arg2:string):Promise<string>;

export function StartDestroySandbox(arg1:string):Promise<string>;

export function StartDestroyWorkspace(arg1:string):Promise<string>;

export function StartDownloadUpdate():Promise<string>;

export function StartFixLocalDomains():Promise<string>;

export function StartGenerateSSHKey(arg1:string):Promise<string>;

export function StartImportFromVPS(arg1:desktopbackend.ImportVPSInput):Promise<string>;

export function StartInstallPackages():Promise<string>;

export function StartJoinWorkspace(arg1:string,arg2:string):Promise<string>;

export function StartLeaveWorkspace(arg1:string,arg2:string):Promise<string>;

export function StartPushToVPS(arg1:desktopbackend.PushInput):Promise<string>;

export function StartRestoreSnapshot(arg1:string,arg2:string):Promise<string>;

export function StartStartSandbox(arg1:string):Promise<string>;

export function StartStopObjectStore():Promise<string>;

export function StartStopSandbox(arg1:string):Promise<string>;

export function StartSyncWorkspace(arg1:string):Promise<string>;

export function StartUpdateSandbox(arg1:desktopbackend.UpdateSandboxInput):Promise<string>;
